spinnaker:
  modules:
    - name: clouddriver
      artifact: clouddriver-web
      properties:
        cf.account.name: gturnquist
        cf.account.password: supersecret
#      patterns:
#        foo: bar
      services:
        - spinnaker-redis
    - name: deck
      artifact: deck-ui
      properties:
        buildpack: staticfile_buildpack
    - name: echo
      artifact: echo-web
    - name: front50
      artifact: front50-web
      services:
        - spinnaker-redis
    - name: gate
      artifact: gate-web
      services:
        - spinnaker-redis
    - name: igor
      artifact: igor-web
    - name: orca
      artifact: orca-web
      services:
        - spinnaker-redis
  properties:
    spring.config.location: https://raw.githubusercontent.com/{org}/spinnaker-config/{label}/spinnaker.yml,https://raw.githubusercontent.com/{org}/spinnaker-config/{label}/spinnaker-local.yml,https://raw.githubusercontent.com/{org}/spinnaker-config/{label}/{module}.yml,https://raw.githubusercontent.com/{org}/spinnaker-config/{label}/{module}-local.yml
    redis.configuration.secure: true
    services.default.protocol: http
    services.echo.host: echo.{domain}
    services.echo.port: 80
  patterns:
    org: gregturn
    label: white
    domain: {deck.domain}

security:
  user:
    name: user
    password: password

multipart:
  max-file-size: 100Mb
  max-request-size: 100Mb

logging:
  level:
    cloudfoundry-client: DEBUG
    reactor:
      core: DEBUG
    org:
      cloudfoundry: DEBUG
      springframework:
#        web: TRACE
        cloud:
          deployer: DEBUG
          spinnaker: DEBUG
